/*
 * @Author: i4season.xiang
 * @Date: 2021-05-07 19:09:05
 * @LastEditTime: 2021-05-07 20:45:20
 * @FilePath: \curtain (2)\example\IAP\IAP_Text\Source\src\TEST.C
 */

void Low_power_wasteGpioASet(void)
{
	AFIO_GPxConfig(GPIO_PA, AFIO_PIN_4, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOA, GPIO_PIN_4, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOA, GPIO_PIN_4, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOA, GPIO_PIN_4, DISABLE);
	GPIO_WriteOutBits(HT_GPIOA, GPIO_PIN_4,SET);

	AFIO_GPxConfig(GPIO_PA, AFIO_PIN_5, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOA, GPIO_PIN_5, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOA, GPIO_PIN_5, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOA, GPIO_PIN_5, DISABLE);
	GPIO_WriteOutBits(HT_GPIOA, GPIO_PIN_5,SET);

	AFIO_GPxConfig(GPIO_PA, AFIO_PIN_6, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOA, AFIO_PIN_6, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOA, AFIO_PIN_6, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOA, AFIO_PIN_6, DISABLE);
	GPIO_WriteOutBits(HT_GPIOA, AFIO_PIN_6,SET);

	AFIO_GPxConfig(GPIO_PA, AFIO_PIN_7, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOA, AFIO_PIN_7, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOA, AFIO_PIN_7, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOA, AFIO_PIN_7, DISABLE);
	GPIO_WriteOutBits(HT_GPIOA, AFIO_PIN_7,RESET);

	AFIO_GPxConfig(GPIO_PA, AFIO_PIN_8, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOA, AFIO_PIN_8, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOA, AFIO_PIN_8, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOA, AFIO_PIN_8, DISABLE);
	GPIO_WriteOutBits(HT_GPIOA, AFIO_PIN_8,RESET);

	AFIO_GPxConfig(GPIO_PA, AFIO_PIN_10, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOA, GPIO_PIN_10, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOA, GPIO_PIN_10, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOA, GPIO_PIN_10, DISABLE);
	GPIO_WriteOutBits(HT_GPIOA, GPIO_PIN_10,RESET);

	AFIO_GPxConfig(GPIO_PA, AFIO_PIN_11, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOA, GPIO_PIN_11, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOA, GPIO_PIN_11, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOA, GPIO_PIN_11, DISABLE);
	GPIO_WriteOutBits(HT_GPIOA, GPIO_PIN_11,RESET);


}

void Low_power_wasteGpioBSet(void)
{
	AFIO_GPxConfig(GPIO_PB, AFIO_PIN_0, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOB, AFIO_PIN_0, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOB, AFIO_PIN_0, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOB, AFIO_PIN_0, DISABLE);
	GPIO_WriteOutBits(HT_GPIOB, AFIO_PIN_0,RESET);
	
	AFIO_GPxConfig(GPIO_PB, AFIO_PIN_1, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOB, AFIO_PIN_1, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOB, AFIO_PIN_1, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOB, AFIO_PIN_1, DISABLE);
	GPIO_WriteOutBits(HT_GPIOB, AFIO_PIN_1,RESET);

	AFIO_GPxConfig(GPIO_PB, AFIO_PIN_2, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOB, AFIO_PIN_2, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOB, AFIO_PIN_2, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOB, AFIO_PIN_2, DISABLE);
	GPIO_WriteOutBits(HT_GPIOB, AFIO_PIN_2,RESET);

	AFIO_GPxConfig(GPIO_PB, AFIO_PIN_3, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOB, AFIO_PIN_3, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOB, AFIO_PIN_3, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOB, AFIO_PIN_3, DISABLE);
	GPIO_WriteOutBits(HT_GPIOB, AFIO_PIN_3,RESET);

	AFIO_GPxConfig(GPIO_PB, AFIO_PIN_4, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOB, AFIO_PIN_4, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOB, AFIO_PIN_4, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOB, AFIO_PIN_4, DISABLE);
	GPIO_WriteOutBits(HT_GPIOB, AFIO_PIN_4,SET);

	AFIO_GPxConfig(GPIO_PB, AFIO_PIN_5, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOB, AFIO_PIN_5, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOB, AFIO_PIN_5, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOB, AFIO_PIN_5, DISABLE);
	GPIO_WriteOutBits(HT_GPIOB, AFIO_PIN_5,SET);

	AFIO_GPxConfig(GPIO_PB, AFIO_PIN_6, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOB, AFIO_PIN_6, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOB, AFIO_PIN_6, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOB, AFIO_PIN_6, DISABLE);
	GPIO_WriteOutBits(HT_GPIOB, AFIO_PIN_6,RESET);

	AFIO_GPxConfig(GPIO_PB, AFIO_PIN_9, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOB, AFIO_PIN_9, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOB, AFIO_PIN_9, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOB, AFIO_PIN_9, DISABLE);
	GPIO_WriteOutBits(HT_GPIOB, AFIO_PIN_9,RESET);

}

void Low_power_wasteGpioCSet(void)
{

	AFIO_GPxConfig(GPIO_PC, AFIO_PIN_0, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOC, AFIO_PIN_0, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOC, AFIO_PIN_0, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOC, AFIO_PIN_0, DISABLE);
	GPIO_WriteOutBits(HT_GPIOC, AFIO_PIN_0,RESET);
	
	AFIO_GPxConfig(GPIO_PC, AFIO_PIN_1, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOC, AFIO_PIN_1, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOC, AFIO_PIN_1, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOC, AFIO_PIN_1, DISABLE);
	GPIO_WriteOutBits(HT_GPIOC, AFIO_PIN_1,SET);

	AFIO_GPxConfig(GPIO_PC, AFIO_PIN_2, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOC, AFIO_PIN_2, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOC, AFIO_PIN_2, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOC, AFIO_PIN_2, DISABLE);
	GPIO_WriteOutBits(HT_GPIOC, AFIO_PIN_2,SET);

	AFIO_GPxConfig(GPIO_PC, AFIO_PIN_3, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOC, AFIO_PIN_3, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOC, AFIO_PIN_3, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOC, AFIO_PIN_3, DISABLE);
	GPIO_WriteOutBits(HT_GPIOC, AFIO_PIN_3,RESET);

	AFIO_GPxConfig(GPIO_PC, AFIO_PIN_4, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOC, AFIO_PIN_4, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOC, AFIO_PIN_4, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOC, AFIO_PIN_4, DISABLE);
	GPIO_WriteOutBits(HT_GPIOC, AFIO_PIN_4,RESET);

	AFIO_GPxConfig(GPIO_PC, AFIO_PIN_5, AFIO_MODE_1);
	GPIO_DirectionConfig(HT_GPIOC, AFIO_PIN_5, GPIO_DIR_OUT);
	GPIO_PullResistorConfig(HT_GPIOC, AFIO_PIN_5, GPIO_PR_DISABLE);
	GPIO_InputConfig(HT_GPIOC, AFIO_PIN_5, DISABLE);
	GPIO_WriteOutBits(HT_GPIOC, AFIO_PIN_5,RESET);
}

void Low_power_wasteGpioSet(void)
{
	Low_power_wasteGpioASet();
	Low_power_wasteGpioBSet();
	Low_power_wasteGpioCSet();
	
}